DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS answer;
DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS reply;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    profile INTEGER NOT NULL DEFAULT 0,
    password TEXT NOT NULL
);

CREATE TABLE question(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT,
    legend TEXT,
    level INTEGER NOT NULL DEFAULT 0,
    category INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE image(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question_id INTEGER NOT NULL,
    path TEXT NOT NULL,        
    FOREIGN KEY (question_id) REFERENCES question(id)
);

CREATE TABLE answer(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    body TEXT DEFAULT NULL,
    solution INTEGER NOT NULL DEFAULT 0, 
    FOREIGN KEY (question_id) REFERENCES question(id)
);

CREATE TABLE session(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    size INTEGER,
    score INTEGER,
    FOREIGN KEY (user_id) REFERENCES user(id)
);